config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'

  get '/setup/step_1', :to=> 'setup#step_1'
  post '/setup/step_2', :to=> 'setup#step_2'
  post '/setup/step_3', :to=> 'setup#step_3'
  post '/setup/step_4', :to=> 'setup#step_4'
  
  get '/themes/upload', :to=> 'theme#upload'
  post '/themes/upload', :to=> 'theme#create'
  

  get '/blog/:id/:name', :to=> 'posts#show'
  
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
  match '/auth/destroy', :to => 'sessions#destroy', via: [:delete]
  
  get '/about', :to => 'about#index'
  get '/about/edit', :to => 'about#edit'
  post '/about/edit', :to => 'about#update'
  get "/admin", :to => 'admin#index'
  get "/admin/settings", :to => 'admin#settings'
  post "/admin/settings", :to => 'admin#update'

  resources :categories
  resources :posts

end

app/views/admin/index.html.erb
<div id="vb_admin_main">
<div id="vb_admin_posts">
  <h2>
    posts
  </h2>
  <div id="vb_admin_posts_per_page">
    <small>posts per page</small><br/>
    <%=[10, 20, 50, 100].collect do |n|

      (link_to n, "/admin?posts_per_page=#{n}", :class=> (@posts_per_page == n)? "current_posts_per_page":" " ) + "&nbsp;".html_safe
    end.join.html_safe%>
  </div>
  <table>
    <thead>
      <tr>
        <% %w[updated_at title category views published].each do |h|%>
          <th>
            <%=link_to h.gsub('_',' '), "/admin?sort_posts_by=#{url_encode(h)}&desc=#{!to_bool(params[:desc])}", :title=>"sort posts by #{h}"%>
          </th>
        <%end%> 
    	</tr>
      </thead>
      <tbody>
        <%@posts.each do |post|%>
          <tr>
            <td><small><%=post.updated_at.strftime "%-m/%d/%y" %></small></td>
            <td><%=link_to post.title, edit_post_path(post.id) %></td>
            <td><%=post.category.name%></td>
            <td><%=post.views%></td>
            <td>
              <span data-published=<%=post.published%> title="<%=(post.published)? 'Published':'Not published'%>">
                <%= (post.published)? "yes" : "no"%>
              </span>
            </td>
          </tr>  
        <%end%>  
    </tbody>    
  </table> 
</div>

<div id="vb_admin_categories">
  <h2>
    categories
  </h2>
  <table>
    <tbody>
  	  <%@categories.each do |cat|%>
  	  <tr>
  	  	<td>
  	  	  <%=link_to cat.name, edit_category_path(cat)%>
  	  	</td>
        <td>
          <%=link_to cat.posts.length.to_s + " posts", cat%>
        </td>  
  	  	<% if @categories.length > 1 && cat.posts.length < 1%>
  	  	<td>
  	  	  <%= link_to 'remove', cat, method: :delete%>
	  	</td>
	  	<%end%>
	   </tr> 	
	 <%end%>
  	</tbody>
  </table>
</div>
</div>

app/views/admin/settings.html.erb
<%unless flash[:errors].nil?%>
  <div id="vb_flash_messages">
    <%=flash[:errors]%>
  </div>
<%end%>  
<div id="vb_form">
  <%=form_tag "/admin/settings", :method=>"POST" do %>
  <div class="vb_admin_inputs">
    <%=label_tag :headline%>
    <small>This is the headline for your blog.</small>
    <%=text_field_tag "blog[title]", @blog.title%>
  </div>    

  <h2>
    themes
  </h2>
  <div id="vb_admin_themes" class="vb_admin_inputs">
  <%=label_tag :select_theme%>
  <select name="blog[theme]">
  <%@themes.each do |theme|%>
    <option value="<%=theme.name%>" <%=(theme.name == @blog.theme)? "selected" : ""%>>
      <%=theme.name%>
    </option> 
  <%end%>
  </select>
  <%=link_to "add theme..", "/themes/upload"%>
</div>
<div id="vb_admin_social">
  <ul>
  <%unless @blog.social.nil?
    @blog.social.each do |name, value|%>
      <input type="hidden" name="blog[social][<%=name%>]" value="<%=value%>">
      <li><%=name%> == <%=value%></li>
    <%end%>
  <%end%>
  </ul>
  
  add social site! 
  <input type="text" name = "blog[social]"%>
</div>

  <div class="vb_admin_inputs">
    <%= submit_tag %>
    <%= link_to 'cancel', :back %>
  </div>  
<%end%>
</div>