config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'

  get '/setup/step_1', :to=> 'setup#step_1'
  post '/setup/step_2', :to=> 'setup#step_2'
  post '/setup/step_3', :to=> 'setup#step_3'
  post '/setup/step_4', :to=> 'setup#step_4'
  
  get '/themes/upload', :to=> 'theme#upload'
  post '/themes/upload', :to=> 'theme#create'
  

  get '/blog/:id/:name', :to=> 'posts#show'
  
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
  match '/auth/destroy', :to => 'sessions#destroy', via: [:delete]
  
  get '/about', :to => 'about#index'
  get '/about/edit', :to => 'about#edit'
  post '/about/edit', :to => 'about#update'
  get "/admin", :to => 'admin#index'
  get "/admin/settings", :to => 'admin#settings'
  post "/admin/settings", :to => 'admin#update'

  resources :categories
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	validates_presence_of :title, :description, :body
    validates_inclusion_of :published, :in => [true, false]
	validates_uniqueness_of :title

def vanity_url
  "/blog/#{self.id}/"+Rack::Utils.escape(self.title)
end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :login, only: [:edit, :update, :destroy, :new]
  before_action :cat_all, only: [:edit, :update, :create, :new]
  before_action :set_sidebar_vars, only: [:index, :show]
  

  def index
    params[:sort_by] = params[:sort_by] || "updated_at"
    order = params[:sort_by] == "title"? "ASC" : "DESC"
    @posts = Post.where('published = true').paginate(:page => params[:page], :per_page =>10).order("#{params[:sort_by]} #{order}")

  end

  def show
    @post.increment!(:views, 1)
  end

  def new
    @post = Post.new
    render :layout => 'admin'
    
  end

  def edit
    render :layout => 'admin'
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to "/admin", notice: 'Post was successfully created.'
    else
      flash.now[:errors] = "Unable to save post. " + @post.errors.full_messages.join(', ')
      render :new, :layout => 'admin'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to "/admin", notice: 'Post was successfully updated.' 
    else
      flash.now[:errors] = "Unable to save post. " + @post.errors.full_messages.join(', ')
      render :new, :layout => 'admin' 
    end
  end

  def destroy
    @post.destroy
    redirect_to "/admin", notice: 'Post was successfully destroyed.' 
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description, :body, :category_id, :published, :cover_image)
    end
    
    def cat_all
     @categories = Category.all
    end 

    
end

app/views/posts/_form.html.erb
<%unless flash[:errors].nil?%>
  <div id="vb_flash_messages">
    <%=flash[:errors]%>
  </div>
<%end%>  
<div id="vb_form">
<%= form_for(@post) do |f| %>
  <div class="vb_admin_inputs">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <small>This is a short teaser, describing your post.</small>
    <%= f.text_area :description %>
    <%= f.label :cover_image %>
    <small>The URL of the image that will show for this post in search results.</small>
    <%= f.text_field :cover_image %>
    <%= f.label :published %>
    <div id="vb_admin_post_form_published_tags">
      <label><%= f.radio_button :published, true, checked: @post.published%><span>yes</span></label>
      <label><%= f.radio_button :published, false, checked: !@post.published %><span>no</span></label>
    </div>
    <%=label_tag :category_id%>
    <div id="vb_admin_post_form_category_tags">
      <%@categories.each do |cat|%>
        <label>
          <%= f.radio_button(:category_id, cat.id, {checked: cat.id == @post.category_id, :required=>true})+ "<span>#{cat.name}</span>".html_safe%>  
        </label>
      <%end%>
    </div>  
  </div>
  <%= f.text_area :body, :id=>"textEditor" %>
  <div class="vb_admin_inputs">
    <%= f.submit %>
    <%= link_to 'cancel', :back %>
  </div>  
<% end %>
<script type="text/javascript" src="/assets/javascripts/ckInjector.js"></script>
<script type="text/javascript">
  ckInjector(textEditor);
</script>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h2>
  posts
</h2>

<div id="vb_primary">
<div id="vb_sort_by">
  <p>
    sort by:
  </p>
  <%=link_to "alphabetical", "/posts?sort_by=title" %>
  <%=link_to "most popular", "/posts?sort_by=views" %>
  <%=link_to "most recent", "/posts?sort_by=updated_at" %>
</div>
<div>
<%@posts.each do |post|%>
  <div class="vb_post_block">
    <%=link_to(post.vanity_url, :class=>"vb_post") do%>
      <div class="vb_post_block_date">
        <span><%=post.updated_at.strftime "%d %b %Y"%></span>
      </div>
    <%end%>
    <%=link_to(post.vanity_url, :class=>"vb_post") do%>
      <h3>
        <%=post.title%>
      </h3>
    <%end%>
    <%=link_to post.category.name, "/categories/#{u (post.category.name)}", {:class=>"vb_post_block_category"}%>
    <%=link_to(post.vanity_url, :class=>"vb_post") do%>
      <p>
        <%=post.description%>
      </p>  
    <%end%>
  </div>
<%end%>

<%= will_paginate @posts %>  
</div>
</div>
<%=render 'sidebar' %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div id="vb_post">
  <div id="vb_breadcrumbs">
    <%=link_to "home", root_path%>
    &#8594;
    <%=link_to "posts", posts_path%>
    &#8594;
    <%=link_to @post.category.name, "/categories/#{@post.category.name}"%>
  </div>
  <div id="vb_primary">
    <h2 id="vb_post_headline">
      <%=@post.title%>
    </h2>
    <div id="vb_post_description" itemprop="description">
      <img id="vb_post_cover_image" itemprop="image" src="<%=@post.cover_image%>" alt="<%=@post.title%>"/>
      <%=@post.description%>
    </div>
    <div id="vb_post_published" itemprop="datePublished" content="<%=@post.updated_at%>">
     <p>Published on <b><%=@post.updated_at.strftime("%b %d, %Y")%></b> by <b><%=link_to @blog.author, @blog.google_plus+"?rel=author"%></b></p>
    </div>
    <div itemprop="articleBody">  
      <%=@post.body.html_safe%>
    </div>
    <div id="vb_disqus">
      <div id="disqus_thread"></div>
      <script type="text/javascript">
        var disqus_shortname = '<%=API_KEYS["disqus"]["shortname"]%>';
        var disqus_title = '<%=@post.title%>';
        var disqus_identifier = '<%@post.id%>';
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
      </script>
    </div>
  </div>
  <%=render 'sidebar' %>
 