config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'

  get '/setup/step_1', :to=> 'setup#step_1'
  post '/setup/step_2', :to=> 'setup#step_2'
  post '/setup/step_3', :to=> 'setup#step_3'
  post '/setup/step_4', :to=> 'setup#step_4'
  
  get '/themes/upload', :to=> 'theme#upload'
  post '/themes/upload', :to=> 'theme#create'
  

  get '/blog/:id/:name', :to=> 'posts#show'
  
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
  match '/auth/destroy', :to => 'sessions#destroy', via: [:delete]
  
  get '/about', :to => 'about#index'
  get '/about/edit', :to => 'about#edit'
  post '/about/edit', :to => 'about#update'
  get "/admin", :to => 'admin#index'
  get "/admin/settings", :to => 'admin#settings'
  post "/admin/settings", :to => 'admin#update'

  resources :categories
  resources :posts

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Admin Dashboard</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="/assets/javascripts/velociblogger.js"></script>
  <script src="/assets/javascripts/jquery_ujs.js"></script>
  <link rel="stylesheet" href="/assets/stylesheets/admin.css" type="text/css"/>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="loadCurtain" style="position:fixed; top:0; left:0; width:100%; height:100%; background:white; margin:0;">
</div>
<div id="vb_notification">
<p id="notice"><%= flash[:notice] %></p>
<p id="alert"><%= alert %></p>
</div>
<header id="vb_admin_header">
  <h1>
  	<a href="/admin">
  	  Admin Dashboard
    </a>
  </h1>
  <button id="vb_admin_menu_toggle" onclick="$('#vb_admin_nav').toggleClass('show_nav');">menu</button>
  <nav id="vb_admin_nav">
  <%=link_to "view live site", "/"%>
  <%=link_to "new post", new_post_path%>
  <%=link_to "new category", new_category_path%>
  <%=link_to "edit about page", "/about/edit"%>
  <%=link_to "settings", "/admin/settings"%>
  </nav>
</header>
<%= yield %>
<footer id="vb_admin_footer">
  <script type="text/javascript">
    $(document).ready(function () 
    {
      applyTheme();
      $('#loadCurtain').fadeOut();
    });
  </script>
  <script type="text/javascript">
    $('body').click(function(e){
      if($(e.target).attr('id') != 'vb_admin_menu_toggle'){
        
        $('#vb_admin_nav').removeClass('show_nav');
      }
    });
  </script>
</footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%=Rails.application.class.parent.to_s%></title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="/assets/javascripts/velociblogger.js"></script>
  <script src="/assets/javascripts/jquery_ujs.js"></script>
  <script type="text/javascript" src="/themes/<%=@blog.theme%>/javascripts/theme.js"></script>
  <link rel="stylesheet" href="/themes/<%=@blog.theme%>/stylesheets/theme.css" type="text/css"/>
  <%= csrf_meta_tags %>
</head>
<body class="<%=controller_name%>_<%=action_name%>">
<div id="loadCurtain" style="position:fixed; top:0; left:0; width:100%; height:100%; background:white; margin:0;">
  <noscript>
    Sorry, but JavaScript must be enable to view this page.
  </noscript>
</div>
<div id="vb_notification">
<p id="vb_notification_notice"><%= flash[:notice] %></p>
<p id="vb_notification_alert"><%= flash[:alert] %></p>
</div>
<header id="vb_header">
  <h1>
  	<a href="/">
  	  <%=@blog.title%>
  	</a>
  </h1>
  <nav>
    <a href="/about">
      about
    </a>
    <a href="/posts">
      posts
    </a>
    <a href="/categories">
      categories
    </a>
    <%=if is_admin? then link_to "admin","/admin" end%> 
  </nav>
</header>
<%= yield %>
<footer id="vb_footer">

  <script type="text/javascript">
    $(document).ready(function () 
    {
      applyTheme();
      $('#loadCurtain').fadeOut();
    });
  </script>
</footer>
</body>
</html>

app/views/layouts/setup.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Admin Dashboard</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="/assets/javascripts/velociblogger.js"></script>
  <script src="/assets/javascripts/jquery_ujs.js"></script>
  <link rel="stylesheet" href="/assets/stylesheets/setup.css" type="text/css"/>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="loadCurtain" style="position:fixed; top:0; left:0; width:100%; height:100%; background:white; margin:0;">
</div>
<div id="vb_notification">
<p id="notice"><%= flash[:notice] %></p>
<p id="alert"><%= alert %></p>
</div>
<header id="vb_setup_header">
  <h1>
    setting up your Velociblogger app
  </h1>
  <nav id="vb_setup_nav">
  </nav>
</header>
<%= yield %>
<footer id="vb_setup_footer">
  <script type="text/javascript">
    $(document).ready(function () 
    {
      applyTheme();
      $('#loadCurtain').fadeOut();
    });
  </script>
  
</footer>
</body>
</html>